### ISSUE TITLE
FakeHelpers don't work with netstandard2.0 framework

### ISSUE THREAD

**Issue by ds185357** [fsprojects/fantomas#2049]
When using `FakeHelpers.checkCode` and `FakeHelpers.formatCode` from a .fsx script I'm getting the following error when running `dotnet fake build -t CheckCodeFormat`:

Script is not valid:
        unknown (1,0)-(1,0): Error FS0193: The module/namespace 'System' from compilation unit 'netstandard' did not contain the namespace, module or type 'IAsyncDisposable'

This problem is related to using async inside netstandard2.0 project. This should be simply fixed by targeting netstandard2.1 instead in the Fantomas.Extras.fsproj.

The version used are Fantomas.Extras (4.6.0), fake-cli(5.21.0).

## Example code excerpt:
// The commented code below is working and currently used instead of using FakeHelpers
//Target.create "CheckCodeFormat" (fun _ ->
//    let checkCodeResult =
//        filesToCheckCodeOn
//        |> Seq.map (sprintf "\"%s\"")
//        |> String.concat " "
//        |> sprintf "%s --check"
//        |> DotNet.exec id "fantomas"

//    if checkCodeResult.ExitCode = 0 then
//        Trace.log "No files need formatting"
//    elif checkCodeResult.ExitCode = 99 then
//        failwith "Some files need formatting, check output for more info"
//    else
//        Trace.logf "Errors while formatting: %A" checkCodeResult.Errors)

// The code below DOES NOT WORK because of async
Target.create "CheckCodeFormat" (fun _ ->
    let checkCodeResult =
        FakeHelpers.checkCode filesToCheckCodeOn
        |> Async.RunSynchronously
    if (checkCodeResult.HasErrors) then Trace.traceErrorfn "Errors: %A" checkCodeResult.Errors
    if (checkCodeResult.NeedsFormatting) then
        Trace.traceErrorfn
            "The following F# source files need to be reformatted. Run \"dotnet fake build -t FormatCode\" to reformat them:\n%A"
            checkCodeResult.Formatted
    if (checkCodeResult.HasErrors || checkCodeResult.NeedsFormatting) then failwith "F# code format check failed")

**Comment by ds185357** [comment]
Thank you for your reply. I think the fix should be as simple as increasing the netstandard version however, if you plan to remove the FakeHelpers altogether in the future, feel free to disregard this issue if you want. I'm fine with using the dotnet tool to run Fantomas tasks.

Have a nice day.

**Comment by nojaf** [comment]
Thanks for understanding.
